---
- name: "Include {{ ansible_distribution }}-specific variables"
  include_vars: "{{ ansible_distribution }}.yml"

- name: Include FTSConfig variables
  include_vars: "FTSConfig.yml"

- name: Set ZeroTier IPv4
  set_fact:
    fts_public_ipv4: "{{ zerotierip }}"

- name: Print IPv4
  debug:
    msg: "fts_public_ipv4 = {{ fts_public_ipv4 }}"

- name: Set localhost IPv4
  set_fact:
    fts_ipv4: 127.0.0.1

- name: Setup
  include_tasks: "setup-{{ ansible_distribution }}.yml"

- name: Configure
  include_tasks: "configure-{{ ansible_distribution }}.yml"
