---
- name: "Include {{ ansible_distribution }}-specific variables"
  include_vars: "{{ ansible_distribution }}.yml"

- name: Set ZeroTier IPv4
  set_fact:
    murmur_ipv4: "{{ zerotierip }}"

- name: Print IPv4
  debug:
    msg: "murmur_ipv4 = {{ murmur_ipv4 }}"

- name: Setup
  include_tasks: "setup-{{ ansible_distribution }}.yml"

- name: Configure
  include_tasks: "configure-{{ ansible_distribution }}.yml"

- name: Notify handlers
  shell: ":"
  notify:
    - print murmur ip
    - print murmur credentials
    - print reconfigure message
